### ISSUE TITLE
GRF document outline

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#327]
Please start filling in sections ***

****Note: The following are DUE (for internal review) on OCT 8**
 - [ ] abstract
 - [ ] objectives
 - [ ] pathways to impact statement
 - [ ] background
 - [ ] methodology
 - [ ] references

Application Form Page:
https://www.ugc.edu.hk/eng/rgc/funding_opport/funding_schemes/form.html

Application PDF: 
https://www.ugc.edu.hk/doc/eng/rgc/form/GRF1.pdf

Document in Progress: 
https://docs.google.com/document/d/1rONQWcpPIiVLg57KvRZu0Ta_bO2sOvMunvRD6jLPoIg/edit?usp=sharing

Items in **bold** will require writing...

## PART I SUMMARY OF THE RESEARCH PROPOSAL
- [ ] **Abstract of Research (400 words max)**
- [ ] Special funding template (select more than one box)
### RESEARCH DETAILS
- [ ]  1.	**Project Objectives and Pathways to Impact Statement**
- [ ]  2.	**Background of research, research plan and methodology**
- [ ]  3.	Re-submission of a proposal not supported previously
### PROJECT FUNDING
- [ ]  4.	**Cost and justification**
- [ ]  5.	Existing facilities and major equipment available for this research project (< 400 words)
- [ ]  6.	**Funds secured or to be secured**
- [ ]  7.	**Particulars of PI and Co-Is**
### DECLARATION OF RELATED PROPOSALS & GRANT RECORD
- [ ]  8.	**Grant Record and Related Research Work of Investigator(s).**	 
### ANCILLARY INFORMATION
- [ ]  9.	 Research Ethics / Safety Approval and Access to Government / Official / Private Data and Records
- [ ]  10.	 Release of completion report, data archive possibilities and public access of publications resulting from research funded by the RGC
- [ ]  11.	 **Education Plan, Technology Transfer Plan, Letters of Collaboration and Supporting Documents**
- Appendix 1: Education Plan (up to one A4 page)
- Appendix 2: Technology Transfer Plan (Optional, up to one A4 page)
- Appendix 3: Letters of Collaboration with other research team(s) or university(ies)
- Appendix 4: Other Supporting Documents
- Appendix 5: Other Supporting Documents

**Comment by kennyviperhk** [comment]
like this?
https://docs.google.com/spreadsheets/d/1nl_p2hc1CJ797gFpGKd5E4-mFavNsTa177wbYIQkvn4/edit?usp=sharing

**Comment by dhowe** [comment]
Close, but I want it here, on github. And we don't need every question, just the major sections. Also please locate the current (2019) version of the GRF form.

- [ ] move list to github
- [ ] include only major sections
- [ ] find current GRF form and link it here
- [ ] Consider if there is a way for the 3 of us to collaboratively edit the form online

**Comment by kennyviperhk** [comment]
Application Form Page:
https://www.ugc.edu.hk/eng/rgc/funding_opport/funding_schemes/form.html

Application PDF: 
https://www.ugc.edu.hk/doc/eng/rgc/form/GRF1.pdf


### PART I SUMMARY OF THE RESEARCH PROPOSAL
1.
- [ ]  a.	Particulars of the Project
i.	
ii.
iii.	
iv.	
- [ ] b.	i.	ii.	iii.	iv.	
- [ ]  c.	Abstract of Research (400 words max)
- [ ]  d.	Special funding template (select more than one box)

### Part II DETAILS OF THE RESEARCH PROPOSAL
## RESEARCH DETAILS
- [ ]  1.	Project Objectives and Pathways to Impact Statement
- a.	
- b.	
- [ ]  2.	Background of research, research plan and methodology
- a.	
- b.	i.	ii.	
- c.	Diagrams
- d.	Ref.
- e.	Output (table)
- [ ]  3.	Re-submission of a proposal not supported previously
- a.	
- b.	
- c.	
## PROJECT FUNDING
- [ ]  4.	Cost and justification
- a.	
- A.	i.	ii.	iii.	iv.	v.	
- B.	vi.	vii.	viii.	ix.	x.	
- C.	xi.	xii.	xiii.	
- b.	
- c.	
- d.	
- e.	
- [ ]  5.	Existing facilities and major equipment available for this research project (a maximum of 400 words)
- [ ]  6.	Funds secured or to be secured
- a.	
- b.	
- [ ]  7.	Particulars of PI and Co-Is
- a.	
- b.	i.	ii.	iii.	iv.	v.	vi.	vii.	 
- c.	Plan(s)
- d.	Number of hours per week
## DECLARATION OF RELATED PROPOSALS & GRANT RECORD
- [ ]  8.	Grant Record and Related Research Work of Investigator(s)
- a.	i.	 ii.	 iii.	 (1-9)   iv.	 
- b.	i.	 ii.	 (1-7)iii.	 
## ANCILLARY INFORMATION
- [ ]  9.	 
- a.   i.	 ii.	 (1-7) 	 iii.	 
- b.   i.	 ii.	
- [ ]  10.	 
- a.
- b.   i.	 ii.	 iii.	 
- [ ]  11.	 
- Appendix 1: Education Plan (up to one A4 page)
- Appendix 2: Technology Transfer Plan (Optional, up to one A4 page)
- Appendix 3: Letters of Collaboration with other research team(s) or university(ies)
- Appendix 4: Other Supporting Documents
- Appendix 5: Other Supporting Documents

- [ ]  ### PART III UNIVERSITY’S ENDORSEMENT AND DECLARATION OF RESEARCH ETHICS/SAFETY
(To be completed by the appropriate authority of the university. The university should confirm that it has evaluated and given support to the application before submission to the RGC.)
## UNIVERSITY’S ENDORSEMENT
- 1.	
- a.	 
- b.	 
- c.	 
- d.	 
- e.	 
- f.	 
- g.	 
- h.	 
- i.	 
- j.	 
- k.	 
- l.

**Comment by kennyviperhk** [comment]
https://docs.google.com/document/d/1rONQWcpPIiVLg57KvRZu0Ta_bO2sOvMunvRD6jLPoIg/edit?usp=sharing

**Comment by dhowe** [comment]
Please use the checkboxes above to show what is complete:

![image](https://user-images.githubusercontent.com/737638/65666438-3e700b00-e070-11e9-961f-988c369834f8.png)

**Comment by dhowe** [comment]
Then lets start filling in the sections. Is there a collaborative version that we can edit?

**Comment by kennyviperhk** [comment]
no, they only have a PDF uneditable version, so I converted to google docs as above

https://docs.google.com/document/d/1rONQWcpPIiVLg57KvRZu0Ta_bO2sOvMunvRD6jLPoIg/edit?usp=sharing
