### ISSUE TITLE
Missing Design for Pages

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#462]
@peterbix we are currently missing design for the following installation pages:

- [x] TakeSelfie page (see notes below this list)
- [x] LoginPage with keyboard (#447,  one page, no gender)
- [x] GDPR dialog on LoginPage (see comments on #402)
- [x] Full TOS overlay on LoginPage (#402)
- [x] Take-back-control should have similar design as GDPR (#490 )

Take-Selfie page on the figma is almost there, however we need it show design for the various states on the page:
* countdown (after user presses capture -- or just starts counting down when page loads)
* display of the captured image (after countdown)
* 'take-another' button they can use they don't like current image (this can happen repeatedly)

Note also that this page is presented to the user after 'Data-Is', so it needs to be moved in the figma (I don't seem to have edit perms)

**Comment by peterbix** [comment]
@dhowe I've added Keyboard and TOS dialog and overlay.
However, I do not have a template page for the 'Take selfie' page. Could you send me something?

**Comment by dhowe** [comment]
@billposters do you want to chime in here, as I know you had some ideas about a circular cutout for the head or similar ...

In any case, the current functionality is as below (and visible on the live site). When you press 'capture', It gives you a 3-second countdown to take a picture. The picture then appears in the upper-left corner, and you have the option to 'retake' as many times as you like. When satisfied you can press 'Next' to go on.

![image](https://user-images.githubusercontent.com/737638/74153321-57f2a780-4c4b-11ea-8ad2-cb4ea8eaefdd.png)


![image](https://user-images.githubusercontent.com/737638/74153256-2c6fbd00-4c4b-11ea-8378-dd487931cdcb.png)
