### ISSUE TITLE
Front-end installation UX TODO

### ISSUE THREAD

**Issue by kennyviperhk** [dhowe/spectre#478]
All elements should be visible on Figma [here](https://www.figma.com/file/7s5ylebj7GTnfEA92NouPB/Spectre---Landscape)
- [x] Missing design for pages (#462)
- [x] Login page layout needs slight adjustment. ToS link is located inside virtual keyboard.
- [x] Ocean Profile side tab 
- [x] Login Page GDPR & TOS overlay (#412)
- [x] Login Page Email Pop-up Bubble
- [x] Single Login Page with keyboard (#447, blocked)
- [x] Dark-ad second page
- [x] Dark-ad replace with new logos (democrats/republican)
- [x] Target-ad page (text too small for yes/no, anything else?)
(Page has changed design according to figma already)
- [x] Smile icons and love / hate arrows added to Game
- [x] Correct icons on 'Home Data' page ('smart assistant' placeholder now repeated)
- [x] CSS Tweaks (#479, #490, #475, "Live" icon on avatar profile pics)
- [x] If Democrat party selected, ‘launch campaign’ page says ‘keep america great’. This slogan needs changing to a relevant democrat one.
- [x] Last 2 sentences on OCEAN side bar don't fit on the blue sidebar. All text for this paragraph needs to be a slightly smaller point size, and content on left-side should perhaps slide up
- [x] images in dark ad not correct (done)  

**On-hold / awaiting-assets / needs-verification**
- [ ] Design solution for dark ad slogans (red background color obscures important parts of images -> on-hold)
- [x] brand game icons aren’t readable on some as they move too fast. Can we add ~15~ 5 secs on to the game? (awaiting verification -- see notes below)
- [x] 'next' buttons need activating on insight questions, these are not activated at present when slider choice is made  (touch-screen configuration issue -- see ticket)

**Comment by dhowe** [comment]
@kennyviperhk pls update as things complete

**Comment by billposters** [comment]
just added one more task

**Comment by dhowe** [comment]
> brand game icons aren’t readable on some as they move too fast. Can we add 15 secs on to the game?

it is already 35 seconds (and not very interesting as a game) - we had already decided (in Sheffield) this was the maximum advisable length

I would suggest instead reducing the number of brands, especially those which don't exist or aren't well known in the US (e.g., M&S etc.)

**Comment by billposters** [comment]
good idea. Lets drop those brands. I would suggest: 

8: "h&m"
15: "zara"
22: "new look"
25: "next"
28: "asos"

Question - will this impact OCEAN results, as these are all female leaning clothing brands? Could it impact score accuracy?

**Comment by billposters** [comment]
> it is already 35 seconds (and not very interesting as a game) - we had already decided (in Sheffield) this was the maximum advisable length

- 5 seconds extra time would help legibility, without impacting UX, especially if we drop 5 brands.

- alternative is to make all the icon buttons larger, so the logos are more visible (some have very thin type that isn't legible on screen when moving faster)

**Comment by billposters** [comment]
@kennyviperhk @dhowe - can you do some UX testing on your touchscreen / mac setup in HK over the next 2 days when these FE tasks are completed? 

i'm travelling to London for a meeting with SX funders (Arts Council, british underground), so i can't verify any amendments on touchscreen. 

Tom and i will be back in the space testing the UX etc from Weds. Cheers

**Comment by dhowe** [comment]
> alternative is to make all the icon buttons larger, so the logos are more visible (some have very thin type that isn't legible on screen when moving faster)

yes, would be great if someone can collect proper images for the brands. @oscaryfish (d) originally grabbed them as screencaps from a website. But we actually need them as .svg, which allows them to a) scale properly, and b) look correct when moving

**Comment by billposters** [comment]
> > alternative is to make all the icon buttons larger, so the logos are more visible (some have very thin type that isn't legible on screen when moving faster)
> 
> yes, would be great if someone can collect proper images for the brands. @oscaryfishoriginally grabbed them as screencaps from a website. But we actually need them as .svg, which allows them to a) scale properly, and b) look correct when moving
> 
> meantime, I've increased the size of the images AND removed several duplicate/UK-specific brands (please check)

- ah that's why. Ok I'll source as .svg today and add them here.

**Comment by dhowe** [comment]
closing as all items are fixed or represented in other tickets
