### ISSUE TITLE
Load-in Checklist

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#543]
- [ ] Server connected to static-ip
- [ ] Adjust brightness setting for selfies
- [ ] Clients connected/logged-in to SXSW Wifi
- [ ] Domain spectreknows.me DNS updated
- [ ] Chrome caches enabled (if any lag)
- [ ] [Script](https://rednoise.org/ftp/Spectre-SXSW.app.zip) on desktop and in user's 'Login Items' to launch app on boot
- [ ] All updates/notifications/power-mgmt etc. disabled

**Comment by dhowe** [comment]
closing for now
