### ISSUE TITLE
Remaining UX tasks before Freeze

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#553]
Code-freeze **before** UK 5pm, Tuesday

**DEV-OPS**
- [ ] Cache problem (dh)
- [ ] Script to boot into Spectre (bp testing)

**DESIGN**
- [x] 2nd iteration of Post-Experience (#551)
- [x] OceanProfile: highlight dominant trait (#555)
- [x] Differentiate buttons throughout (#545)
- [x] Fix button display on Insight-complete (#556)

**FRONT-END**
- [x] CSS problem on Login Page (#571, bp)
- [x] All next icon buttons needs blue fill (#570, bp)
- [x] OceanProfile: highlight dominant trait (#565, dh)
- [x] Placeholder images for dark-ad page (#567, bp)
- [x] Ocean sidebar: dynamic/help text missing (intermittent)
- [x] Intermittent slider problem (if not on a specific page, then likely a driver issue)
- [x] Change 'make america great slogan' on N Hi Rep
- [x] Alignment on consumer data page  (#557)
- [x] Fix square brands on game
- [x] Remove 1 x 'Vans' logo from game as duplicated at present
- [x] Move 'Ready?' text slightly lower down on Steps page 
- [x] Change text on Your-Power page
- [x] Ocean-reveal text
- [x] Dark-ad red banner positions

**ASSETS**
- [x] Home-screen video choice
- [x] Square brand images
- [x] Audio for videos (Spectre-Intro, Ocean-Intro)
- [x] Ocean-Intro video merged w' new sound 
- [x] Intro to spectre video merged with new sound
- [x] 1 video-set gets resync (Marina)
- [x] 1 videos get new size (Spectre-Intro)

**Comment by billposters** [comment]
reviewed all Marina videos yesterday, and can't find any sync issues. They are all the same as the final files that were exported that are perfectly synced. So we can sign off this issue now.

**Comment by dhowe** [comment]
Please verify dark-ad banner positioning, OceanProfile, and OceanReveal.
Also check new home-screen video

**Comment by billposters** [comment]
Intro to Ocean video ready for download here: 

https://we.tl/t-qaWQ7WFziY

* still waiting on project file to edit the intro to spectre video...

**Comment by billposters** [comment]
> Please verify dark-ad banner positioning, OceanProfile, and OceanReveal.
> Also check new home-screen video

verified. Good work ol' chap!

**Comment by billposters** [comment]
2 x videos for review: 
1 - intro to spectre
2 - intro to ocean 

DL: https://we.tl/t-3dXJooRUox

* new soundtrack on intro to ocean as the old track is not available. had to re-edit the video for 1920x1080

**Comment by billposters** [comment]
Standby / home screen video re-coloured: 
https://we.tl/t-gczuwufspj

**Comment by billposters** [comment]
Fixed brand icons: 

https://we.tl/t-67K31XMykY

**Comment by dhowe** [comment]
> Fixed brand icons:

All good except for Marvel:

![image](https://user-images.githubusercontent.com/737638/75630240-dd9ebd00-5c23-11ea-99ac-6c821932a7a1.png)

**Comment by billposters** [comment]
Final (v3) UX videos for:
- intro to spectre
- intro to ocean

DL: https://we.tl/t-um7DkxUY2F

**Comment by dhowe** [comment]
Made live (music volume perhaps a touch loud on OCEAN, but fine)

**Comment by peterbix** [comment]
@billposters @dhowe I've completed all design issues. Just one to confirm for you "Biometric: need to add detected age/gender/confidence' to user image (see below)"
Please email me with anything else.

**Comment by dhowe** [comment]
> @billposters @dhowe I've completed all design issues. Just one to confirm for you "Biometric: need to add detected age/gender/confidence' to user image (see below)"

something like this:
![image](https://user-images.githubusercontent.com/737638/75686783-c3261b80-5cd7-11ea-9015-dfedbcff9f24.png)
