### ISSUE TITLE
Email/post TODO

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#580]
**Email**
- [ ] Comment share link
- [ ] All other links to post-exp
- [ ] First sentence: '...especially those that are X,Y,Z'

**PostExp**
- [ ] First sentence?
- [ ] Errors in OCEAN inferences- add short sentence here
- [ ] Update videos / images
- [ ] Dynamic dark-ad ? (what if they haven't got that far)
- [ ] Update images / video links

**Comment by dhowe** [comment]
[POST_EXP_IMAGES.zip](https://github.com/dhowe/spectre/files/4298898/POST_EXP_IMAGES.zip)

**Comment by billposters** [comment]
here's the vimeo link to the sxsw trailer to embed at the top of the post exp webpage: 
https://vimeo.com/395969657
